{"name": "Невозможность создания пользователя с уже существующими данными", "status": "passed", "steps": [{"name": "Создание пользователя", "status": "passed", "parameters": [{"name": "body", "value": "{'email': 'архип.1749394506233@example.com', 'password': 'f99GlDcU8_', 'name': 'Мир'}"}], "start": 1749394506234, "stop": 1749394506412}, {"name": "Создание пользователя", "status": "passed", "parameters": [{"name": "body", "value": "{'email': 'архип.1749394506233@example.com', 'password': 'f99GlDcU8_', 'name': 'Мир'}"}], "start": 1749394506412, "stop": 1749394506485}], "start": 1749394506234, "stop": 1749394506485, "uuid": "e8f013c3-857a-424d-8915-76269f785162", "historyId": "d44112a95b1dd159d5008947d444f422", "testCaseId": "d44112a95b1dd159d5008947d444f422", "fullName": "tests.test_create_user.TestCreateUser#test_create_user_fails_for_duplicate_create", "labels": [{"name": "feature", "value": "Создание пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "DESKTOP-579T290"}, {"name": "thread", "value": "27800-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}